services:
  init-db:
    image: postgres
    hostname: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5532:5432" # Exposes a different port than the default incase another DB is running on the host
    volumes:
      - init-db-data:/var/lib/postgresql/data
volumes:
  init-db-data:
